language: node_js

node_js:
  - "10"

cache:
  directories:
    - ~/.npm
    - node_modules
    - ~/.sonar/cache

addons:
  sonarcloud:
    organization: "mocks-server"
    branch:
      name: "$TRAVIS_CURRENT_BRANCH"

script:
  - npm run lint
  #- npm run test
  - npm run build
  - cd test-e2e/react-app
  - npm ci
  - npm run cypress:install
  - npm run cypress:verify
  - npm run test:ci
  - cd ../..
  - npm run coveralls
  - 'if [ -n "$SONAR_TOKEN" ]; then sonar-scanner -Dsonar.login=${SONAR_TOKEN}; fi'

deploy:
  provider: npm
  email: "javier.brea@gmail.com"
  api_key: "$NPM_TOKEN"
  edge: true
  on:
    tags: true
  skip_cleanup: true
