name: build
on:
  push:
    branches:
      - master
      - release
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12.22.1", "14.17.0", "16.1.0", "17.2.0"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'release'
      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.15.1
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm run lint
      - name: Test unit
        run: pnpm run test:unit:all
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: coverage-${{ matrix.node }}
          path: packages/main/coverage # TODO, merge coverage from all unit tests
          retention-days: 1
  test-e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12.22.1", "14.17.0", "16.1.0", "17.2.0"]
        projectName: ["main-e2e"] # TODO, build matrix dinamically based on affected projects
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.15.1
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Test E2E
        run: pnpm run nx test:e2e ${{ matrix.projectName }}
  coveralls:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download test results
        uses: actions/download-artifact@v2
        with:
          name: coverage-16.1.0
          path: packages/main/coverage # TODO, read merged coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: packages/main/ # TODO, read merged coverage
          path-to-lcov: ./packages/main/coverage/lcov.info # TODO, read merged coverage
  sonar:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        projectName: ["main"] # TODO, build matrix dinamically based on affected projects
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download test results
        uses: actions/download-artifact@v2
        with:
          name: coverage-16.1.0
          path: packages/${{ matrix.projectName }}/coverage # TODO, get projectPath based on projectName from config using sh
      - name: SonarCloud Scan
        if: env.SONAR_TOKEN != ''
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: packages/${{ matrix.projectName }}/ # TODO, get projectPath based on projectName from config using sh
