name: build
on:
  push:
    branches:
      - master
      - release
      - pre-release
      - monorepo-poc
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12.22.1", "14.17.0", "16.1.0", "17.2.0"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: extract-branch
      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.15.1
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm run lint
      - name: Test unit
        run: cd packages/main && pnpm run test:unit
      - name: Test E2E
        run: cd packages/main && pnpm run test:e2e
        id: test-e2e
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: coverage-${{ matrix.node }}
          path: packages/main/coverage
          retention-days: 1
  quality:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download test results
        uses: actions/download-artifact@v2
        with:
          name: coverage-16.1.0
          path: packages/main/coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: packages/main
      - name: SonarCloud Scan
        if: env.SONAR_TOKEN != ''
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: packages/main/
