name: publish-to-github
on:
  push:
    branches:
      - monorepo-poc
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install pnpm
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.15.1
    - run: pnpm install
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://npm.pkg.github.com'
        # Defaults to the user or organization that owns the workflow file
        scope: '@mocks-server'
        cache: 'pnpm'
    - run: pnpm -r publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
